"""create notifications table

Revision ID: 3aa157db1acf
Revises: 
Create Date: 2026-07-15 14:21:15.481423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa157db1acf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the notification'),
    sa.Column('receiver_id', sa.UUID(), nullable=False, comment='UUID of the user receiving the notification'),
    sa.Column('actor_id', sa.UUID(), nullable=False, comment='UUID of the user who performed the action'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Type of notification (e.g., follow, like, comment)'),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='Optional UUID referencing the associated entity (e.g., post_id, comment_id)'),
    sa.Column('message', sa.String(length=500), nullable=False, comment='Text message describing the notification action'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Flag indicating if the receiver has read the notification'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the notification was created'),
    sa.PrimaryKeyConstraint('id'),
    schema='notification_schema'
    )
    op.create_index(op.f('ix_notification_schema_notifications_actor_id'), 'notifications', ['actor_id'], unique=False, schema='notification_schema')
    op.create_index(op.f('ix_notification_schema_notifications_receiver_id'), 'notifications', ['receiver_id'], unique=False, schema='notification_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_schema_notifications_receiver_id'), table_name='notifications', schema='notification_schema')
    op.drop_index(op.f('ix_notification_schema_notifications_actor_id'), table_name='notifications', schema='notification_schema')
    op.drop_table('notifications', schema='notification_schema')
    # ### end Alembic commands ###
