"""create_stories_table

Revision ID: 331498942e74
Revises: c60f12280d7f
Create Date: 2026-07-22 00:40:21.960434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '331498942e74'
down_revision: Union[str, Sequence[str], None] = 'c60f12280d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('object_key', sa.String(length=500), nullable=False),
        sa.Column('caption', sa.Text(), nullable=True),
        sa.Column('mime_type', sa.String(length=100), nullable=False, server_default='image/jpeg'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text("(now() + '1 day'::interval)")),
        sa.PrimaryKeyConstraint('id'),
        schema='post_schema'
    )
    op.alter_column('stories', 'id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the story',
               existing_nullable=False,
               schema='post_schema')
    op.alter_column('stories', 'user_id',
               existing_type=sa.UUID(),
               comment='Owner of the story (references User UUID)',
               existing_nullable=False,
               schema='post_schema')
    op.alter_column('stories', 'object_key',
               existing_type=sa.VARCHAR(length=500),
               comment='MinIO storage object key in temp-media bucket',
               existing_nullable=False,
               schema='post_schema')
    op.alter_column('stories', 'caption',
               existing_type=sa.TEXT(),
               comment='Optional caption text for the story',
               existing_nullable=True,
               schema='post_schema')
    op.alter_column('stories', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment='RFC MIME type descriptor',
               existing_nullable=False,
               existing_server_default=sa.text("'image/jpeg'::character varying"),
               schema='post_schema')
    op.alter_column('stories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when story was uploaded',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='post_schema')
    op.alter_column('stories', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when story expires (24 hours after creation)',
               existing_nullable=False,
               existing_server_default=sa.text("(now() + '1 day'::interval)"),
               schema='post_schema')
    # op.drop_index(op.f('ix_stories_expires_at'), table_name='stories', schema='post_schema')
    # op.drop_index(op.f('ix_stories_user_id'), table_name='stories', schema='post_schema')
    op.create_index(op.f('ix_post_schema_stories_expires_at'), 'stories', ['expires_at'], unique=False, schema='post_schema')
    op.create_index(op.f('ix_post_schema_stories_user_id'), 'stories', ['user_id'], unique=False, schema='post_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_schema_stories_user_id'), table_name='stories', schema='post_schema')
    op.drop_index(op.f('ix_post_schema_stories_expires_at'), table_name='stories', schema='post_schema')
    # op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False, schema='post_schema')
    # op.create_index(op.f('ix_stories_expires_at'), 'stories', ['expires_at'], unique=False, schema='post_schema')
    op.alter_column('stories', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when story expires (24 hours after creation)',
               existing_nullable=False,
               existing_server_default=sa.text("(now() + '1 day'::interval)"),
               schema='post_schema')
    op.alter_column('stories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when story was uploaded',
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='post_schema')
    op.alter_column('stories', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='RFC MIME type descriptor',
               existing_nullable=False,
               existing_server_default=sa.text("'image/jpeg'::character varying"),
               schema='post_schema')
    op.alter_column('stories', 'caption',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional caption text for the story',
               existing_nullable=True,
               schema='post_schema')
    op.alter_column('stories', 'object_key',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='MinIO storage object key in temp-media bucket',
               existing_nullable=False,
               schema='post_schema')
    op.alter_column('stories', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Owner of the story (references User UUID)',
               existing_nullable=False,
               schema='post_schema')
    op.alter_column('stories', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the story',
               existing_nullable=False,
               schema='post_schema')
    op.drop_table('stories', schema='post_schema')
    # ### end Alembic commands ###
