"""create post tables

Revision ID: 40f06ddf158e
Revises: 
Create Date: 2026-07-19 00:24:39.498511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f06ddf158e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the post'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Owner of the post (references User UUID)'),
    sa.Column('caption', sa.Text(), nullable=True, comment='Caption text written for the post'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='Optional tagged location of the post'),
    sa.Column('visibility', sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='postvisibility', schema='post_schema'), nullable=False, comment='Privacy visibility category of the post'),
    sa.Column('comments_enabled', sa.Boolean(), nullable=False, comment='Flag indicating if comment creation is enabled'),
    sa.Column('media_count', sa.Integer(), nullable=False, comment='Cached count of media files in this post'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='Cached count of likes for this post'),
    sa.Column('comment_count', sa.Integer(), nullable=False, comment='Cached count of comments for this post'),
    sa.Column('save_count', sa.Integer(), nullable=False, comment='Cached count of saves for this post'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when post was soft deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when post was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when post was last updated'),
    sa.PrimaryKeyConstraint('id'),
    schema='post_schema'
    )
    op.create_index(op.f('ix_post_schema_posts_user_id'), 'posts', ['user_id'], unique=False, schema='post_schema')
    op.create_table('post_comments',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the comment'),
    sa.Column('post_id', sa.UUID(), nullable=False, comment='Foreign key referencing the associated Post'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Foreign key referencing the User who authored the comment'),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True, comment='Optional self-referencing foreign key for nested comment replies'),
    sa.Column('content', sa.Text(), nullable=False, comment='The text content of the comment'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='Cached count of likes for this comment'),
    sa.Column('reply_count', sa.Integer(), nullable=False, comment='Cached count of nested replies to this comment'),
    sa.Column('is_edited', sa.Boolean(), nullable=False, comment='Flag indicating if the comment was edited'),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when comment content was last edited'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when comment was soft deleted'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when comment was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when comment was last updated'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['post_schema.post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post_schema.posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='post_schema'
    )
    op.create_index(op.f('ix_post_schema_post_comments_parent_comment_id'), 'post_comments', ['parent_comment_id'], unique=False, schema='post_schema')
    op.create_index(op.f('ix_post_schema_post_comments_post_id'), 'post_comments', ['post_id'], unique=False, schema='post_schema')
    op.create_table('post_likes',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the post like record'),
    sa.Column('post_id', sa.UUID(), nullable=False, comment='Foreign key referencing the liked Post'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Foreign key referencing the User who liked the post'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when user liked the post'),
    sa.ForeignKeyConstraint(['post_id'], ['post_schema.posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_user_like'),
    schema='post_schema'
    )
    op.create_table('post_media',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the media item'),
    sa.Column('post_id', sa.UUID(), nullable=False, comment='Foreign key referencing the associated Post'),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', name='mediatype', schema='post_schema'), nullable=False, comment='Type category of this media file (IMAGE or VIDEO)'),
    sa.Column('object_key', sa.String(length=500), nullable=False, comment='MinIO object key storage path for the original media file'),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True, comment='MinIO object key storage path for the video thumbnail file'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Ordering position index inside the post gallery carousel'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='RFC MIME type category descriptor (e.g. image/jpeg, video/mp4)'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='Size of the raw binary payload object in bytes'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Pixel width resolution of the media'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Pixel height resolution of the media'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='Duration length of the video file in seconds'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when media upload occurred'),
    sa.ForeignKeyConstraint(['post_id'], ['post_schema.posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='post_schema'
    )
    op.create_index(op.f('ix_post_schema_post_media_post_id'), 'post_media', ['post_id'], unique=False, schema='post_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_schema_post_media_post_id'), table_name='post_media', schema='post_schema')
    op.drop_table('post_media', schema='post_schema')
    op.drop_table('post_likes', schema='post_schema')
    op.drop_index(op.f('ix_post_schema_post_comments_post_id'), table_name='post_comments', schema='post_schema')
    op.drop_index(op.f('ix_post_schema_post_comments_parent_comment_id'), table_name='post_comments', schema='post_schema')
    op.drop_table('post_comments', schema='post_schema')
    op.drop_index(op.f('ix_post_schema_posts_user_id'), table_name='posts', schema='post_schema')
    op.drop_table('posts', schema='post_schema')
    # ### end Alembic commands ###
