version: '3.8'

services:
  redis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=admin-password
    restart: always
