"""Initial chat schema models creation

Revision ID: dc5ea3aa8d76
Revises: 
Create Date: 2026-07-16 01:47:21.745087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5ea3aa8d76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_one_id', sa.UUID(), nullable=False),
    sa.Column('user_two_id', sa.UUID(), nullable=False),
    sa.Column('last_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('user_one_id <> user_two_id', name='chk_users'),
    sa.ForeignKeyConstraint(['last_message_id'], ['chat_schema.messages.id'], name='fk_last_message', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_one_id', 'user_two_id', name='uq_conversation'),
    schema='chat_schema'
    )
    op.create_index(op.f('ix_chat_schema_conversations_user_one_id'), 'conversations', ['user_one_id'], unique=False, schema='chat_schema')
    op.create_index(op.f('ix_chat_schema_conversations_user_two_id'), 'conversations', ['user_two_id'], unique=False, schema='chat_schema')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('reply_to_message_id', sa.UUID(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('deleted_for_everyone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_schema.conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['chat_schema.messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='chat_schema'
    )
    op.create_index('idx_messages_created_at', 'messages', [sa.literal_column('created_at DESC')], unique=False, schema='chat_schema')
    op.create_index(op.f('ix_chat_schema_messages_conversation_id'), 'messages', ['conversation_id'], unique=False, schema='chat_schema')
    op.create_index(op.f('ix_chat_schema_messages_sender_id'), 'messages', ['sender_id'], unique=False, schema='chat_schema')
    op.create_table('deleted_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_schema.messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_deleted_message'),
    schema='chat_schema'
    )
    op.create_index(op.f('ix_chat_schema_deleted_messages_user_id'), 'deleted_messages', ['user_id'], unique=False, schema='chat_schema')
    op.create_table('message_reads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_schema.messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_reader'),
    schema='chat_schema'
    )
    op.create_index('idx_message_reads_message', 'message_reads', ['message_id'], unique=False, schema='chat_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_reads_message', table_name='message_reads', schema='chat_schema')
    op.drop_table('message_reads', schema='chat_schema')
    op.drop_index(op.f('ix_chat_schema_deleted_messages_user_id'), table_name='deleted_messages', schema='chat_schema')
    op.drop_table('deleted_messages', schema='chat_schema')
    op.drop_index(op.f('ix_chat_schema_messages_sender_id'), table_name='messages', schema='chat_schema')
    op.drop_index(op.f('ix_chat_schema_messages_conversation_id'), table_name='messages', schema='chat_schema')
    op.drop_index('idx_messages_created_at', table_name='messages', schema='chat_schema')
    op.drop_table('messages', schema='chat_schema')
    op.drop_index(op.f('ix_chat_schema_conversations_user_two_id'), table_name='conversations', schema='chat_schema')
    op.drop_index(op.f('ix_chat_schema_conversations_user_one_id'), table_name='conversations', schema='chat_schema')
    op.drop_table('conversations', schema='chat_schema')
    # ### end Alembic commands ###
