"""create_user_schema_tables

Revision ID: ae0a481e7f66
Revises: 
Create Date: 2026-07-12 22:35:56.195631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0a481e7f66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the user profile'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Unique ID referencing the core Auth Service User record'),
    sa.Column('username', sa.String(length=30), nullable=False, comment='Instagram username handle used for search and routing'),
    sa.Column('display_name', sa.String(length=50), nullable=True, comment='Full displayed profile name of the user'),
    sa.Column('bio', sa.String(length=150), nullable=True, comment='Instagram-style bio biography status text (max 150 chars)'),
    sa.Column('profile_picture_url', sa.String(length=1000), nullable=True, comment='URL path pointing to avatar image assets stored in MinIO storage'),
    sa.Column('website', sa.String(length=255), nullable=True, comment='Optional external bio portfolio website URL'),
    sa.Column('is_onboarding_completed', sa.Boolean(), nullable=False, comment='Flag indicating if the user has completed their initial registration onboarding flow'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when user profile record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when user profile record was last updated'),
    sa.PrimaryKeyConstraint('id'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True, schema='user_schema')
    op.create_index(op.f('ix_user_schema_user_profiles_username'), 'user_profiles', ['username'], unique=True, schema='user_schema')
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the block restriction record'),
    sa.Column('blocker_id', sa.UUID(), nullable=False, comment='Foreign key referencing the UserProfile who issued the block'),
    sa.Column('blocked_user_id', sa.UUID(), nullable=False, comment='Foreign key referencing the target UserProfile being blocked'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when block action occurred'),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['user_schema.user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['user_schema.user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_user_id', name='uq_blocker_blocked'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_blocks_blocked_user_id'), 'blocks', ['blocked_user_id'], unique=False, schema='user_schema')
    op.create_index(op.f('ix_user_schema_blocks_blocker_id'), 'blocks', ['blocker_id'], unique=False, schema='user_schema')
    op.create_table('follows',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the follow relationship record'),
    sa.Column('follower_id', sa.UUID(), nullable=False, comment='Foreign key referencing the UserProfile executing the follow action'),
    sa.Column('following_id', sa.UUID(), nullable=False, comment='Foreign key referencing the target UserProfile being followed'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='followstatus', schema='user_schema'), nullable=False, comment='State of follow relationship (PENDING for private accounts, ACCEPTED for public)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when follow action was executed'),
    sa.ForeignKeyConstraint(['follower_id'], ['user_schema.user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['user_schema.user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follower_following'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_follows_follower_id'), 'follows', ['follower_id'], unique=False, schema='user_schema')
    op.create_index(op.f('ix_user_schema_follows_following_id'), 'follows', ['following_id'], unique=False, schema='user_schema')
    op.create_table('privacy_settings',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the privacy setting record'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Foreign key referencing the associated UserProfile'),
    sa.Column('account_visibility', sa.Enum('PUBLIC', 'PRIVATE', name='accountvisibility', schema='user_schema'), nullable=False, comment='Visibility category setting (PUBLIC or PRIVATE)'),
    sa.Column('allow_message_requests', sa.Boolean(), nullable=False, comment='Flag indicating if message requests from non-followers are allowed'),
    sa.Column('show_activity_status', sa.Boolean(), nullable=False, comment='Flag indicating if real-time active status is visible to followers'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when privacy setting was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when privacy setting was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['user_schema.user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='user_schema'
    )
    op.create_index(op.f('ix_user_schema_privacy_settings_user_id'), 'privacy_settings', ['user_id'], unique=True, schema='user_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_schema_privacy_settings_user_id'), table_name='privacy_settings', schema='user_schema')
    op.drop_table('privacy_settings', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_follows_following_id'), table_name='follows', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_follows_follower_id'), table_name='follows', schema='user_schema')
    op.drop_table('follows', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_blocks_blocker_id'), table_name='blocks', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_blocks_blocked_user_id'), table_name='blocks', schema='user_schema')
    op.drop_table('blocks', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_user_profiles_username'), table_name='user_profiles', schema='user_schema')
    op.drop_index(op.f('ix_user_schema_user_profiles_user_id'), table_name='user_profiles', schema='user_schema')
    op.drop_table('user_profiles', schema='user_schema')
    # ### end Alembic commands ###
