"""remove allow_message_requests

Revision ID: d4e1026c9ec4
Revises: b1c2d3e4f567
Create Date: 2026-07-19 00:30:12.769993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e1026c9ec4'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('privacy_settings', 'allow_message_requests', schema='user_schema')
    op.alter_column('user_profiles', 'profile_picture_key',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_comment='MinIO object key for the user avatar image (e.g. users/{uuid}/avatar.jpg)',
               existing_nullable=True,
               schema='user_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'profile_picture_key',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_comment='MinIO object key for the user avatar image (e.g. users/{uuid}/avatar.jpg)',
               existing_nullable=True,
               schema='user_schema')
    op.add_column('privacy_settings', sa.Column('allow_message_requests', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Flag indicating if message requests from non-followers are allowed'), schema='user_schema')
    # ### end Alembic commands ###
