"""remove mfa columns

Revision ID: 200b17e3120a
Revises: b74704fd2493
Create Date: 2026-07-03 15:22:59.450791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200b17e3120a'
down_revision: Union[str, Sequence[str], None] = 'b74704fd2493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'mfa_enabled', schema='auth_schema')
    op.drop_column('credentials', 'mfa_secret', schema='auth_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('mfa_secret', sa.VARCHAR(length=100), autoincrement=False, nullable=True), schema='auth_schema')
    op.add_column('credentials', sa.Column('mfa_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='auth_schema')
    # ### end Alembic commands ###
