"""remove_username

Revision ID: acaa52e2b4ab
Revises: bfd3ccad2527
Create Date: 2026-07-14 23:02:25.600456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acaa52e2b4ab'
down_revision: Union[str, Sequence[str], None] = 'bfd3ccad2527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_login_history_logged_in_at'), table_name='login_history', schema='auth_schema')
    op.drop_index(op.f('ix_auth_login_history_user_id'), table_name='login_history', schema='auth_schema')
    op.create_index(op.f('ix_auth_schema_login_history_logged_in_at'), 'login_history', ['logged_in_at'], unique=False, schema='auth_schema')
    op.create_index(op.f('ix_auth_schema_login_history_user_id'), 'login_history', ['user_id'], unique=False, schema='auth_schema')
    op.drop_index(op.f('ix_auth_password_history_user_id'), table_name='password_history', schema='auth_schema')
    op.create_index(op.f('ix_auth_schema_password_history_user_id'), 'password_history', ['user_id'], unique=False, schema='auth_schema')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth_schema')
    op.drop_index(op.f('ix_auth_users_phone'), table_name='users', schema='auth_schema')
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth_schema')
    op.create_index(op.f('ix_auth_schema_users_email'), 'users', ['email'], unique=True, schema='auth_schema')
    op.create_index(op.f('ix_auth_schema_users_phone'), 'users', ['phone'], unique=True, schema='auth_schema')
    op.drop_column('users', 'username', schema='auth_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False), schema='auth_schema')
    op.drop_index(op.f('ix_auth_schema_users_phone'), table_name='users', schema='auth_schema')
    op.drop_index(op.f('ix_auth_schema_users_email'), table_name='users', schema='auth_schema')
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=True, schema='auth_schema')
    op.create_index(op.f('ix_auth_users_phone'), 'users', ['phone'], unique=True, schema='auth_schema')
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth_schema')
    op.drop_index(op.f('ix_auth_schema_password_history_user_id'), table_name='password_history', schema='auth_schema')
    op.create_index(op.f('ix_auth_password_history_user_id'), 'password_history', ['user_id'], unique=False, schema='auth_schema')
    op.drop_index(op.f('ix_auth_schema_login_history_user_id'), table_name='login_history', schema='auth_schema')
    op.drop_index(op.f('ix_auth_schema_login_history_logged_in_at'), table_name='login_history', schema='auth_schema')
    op.create_index(op.f('ix_auth_login_history_user_id'), 'login_history', ['user_id'], unique=False, schema='auth_schema')
    op.create_index(op.f('ix_auth_login_history_logged_in_at'), 'login_history', ['logged_in_at'], unique=False, schema='auth_schema')
    # ### end Alembic commands ###
