"""remove_refresh_session

Revision ID: bfd3ccad2527
Revises: fa28aa12f667
Create Date: 2026-07-12 01:37:10.036048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfd3ccad2527'
down_revision: Union[str, Sequence[str], None] = 'fa28aa12f667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_refresh_sessions_expires_at'), table_name='refresh_sessions', schema='auth_schema')
    op.drop_index(op.f('ix_auth_refresh_sessions_user_id'), table_name='refresh_sessions', schema='auth_schema')
    op.drop_table('refresh_sessions', schema='auth_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('browser', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], name=op.f('refresh_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_sessions_pkey')),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False, schema='auth_schema')
    op.create_index(op.f('ix_auth_refresh_sessions_expires_at'), 'refresh_sessions', ['expires_at'], unique=False, schema='auth_schema')
    # ### end Alembic commands ###
