"""Sync models

Revision ID: fa28aa12f667
Revises: 200b17e3120a
Create Date: 2026-07-08 15:13:05.765912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa28aa12f667'
down_revision: Union[str, Sequence[str], None] = '200b17e3120a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('browser', sa.String(length=80), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('logged_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_login_history_logged_in_at'), 'login_history', ['logged_in_at'], unique=False, schema='auth_schema')
    op.create_index(op.f('ix_auth_login_history_user_id'), 'login_history', ['user_id'], unique=False, schema='auth_schema')
    op.create_table('password_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_password_history_user_id'), 'password_history', ['user_id'], unique=False, schema='auth_schema')
    op.create_table('refresh_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=80), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_refresh_sessions_expires_at'), 'refresh_sessions', ['expires_at'], unique=False, schema='auth_schema')
    op.create_index(op.f('ix_auth_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False, schema='auth_schema')
    op.drop_table('sessions', schema='auth_schema')
    op.drop_table('credentials', schema='auth_schema')
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True), schema='auth_schema')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False), schema='auth_schema')
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False), schema='auth_schema')
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), nullable=False), schema='auth_schema')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False,
               schema='auth_schema')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='auth_schema')
    op.create_index(op.f('ix_auth_users_phone'), 'users', ['phone'], unique=True, schema='auth_schema')
    op.drop_column('users', 'is_verified', schema='auth_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='auth_schema')
    op.drop_index(op.f('ix_auth_users_phone'), table_name='users', schema='auth_schema')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='auth_schema')
    op.alter_column('users', 'username',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='auth_schema')
    op.drop_column('users', 'is_phone_verified', schema='auth_schema')
    op.drop_column('users', 'is_email_verified', schema='auth_schema')
    op.drop_column('users', 'password_hash', schema='auth_schema')
    op.drop_column('users', 'phone', schema='auth_schema')
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_changed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], name=op.f('credentials_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credentials_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('credentials_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='auth_schema'
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('browser', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_seen', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_schema.users.id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey')),
    schema='auth_schema'
    )
    op.drop_index(op.f('ix_auth_refresh_sessions_user_id'), table_name='refresh_sessions', schema='auth_schema')
    op.drop_index(op.f('ix_auth_refresh_sessions_expires_at'), table_name='refresh_sessions', schema='auth_schema')
    op.drop_table('refresh_sessions', schema='auth_schema')
    op.drop_index(op.f('ix_auth_password_history_user_id'), table_name='password_history', schema='auth_schema')
    op.drop_table('password_history', schema='auth_schema')
    op.drop_index(op.f('ix_auth_login_history_user_id'), table_name='login_history', schema='auth_schema')
    op.drop_index(op.f('ix_auth_login_history_logged_in_at'), table_name='login_history', schema='auth_schema')
    op.drop_table('login_history', schema='auth_schema')
    # ### end Alembic commands ###
